"""00_CATALOG_OF_ALL_FILES.md, tag map and work packets — all generated from state.

Nobody edits the catalog by hand any more: it is rebuilt from `.mbset/state.json`
(`mbset.py catalog`). Its table keeps the Tag / tagSuggere / Year cells that
`build_module_template.py --catalog` reads.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .common import Module, dump_json, load_json, now


def _row(module: Module, src: dict[str, Any]) -> list[str]:
    t = src.get("triage", {})
    tags = src.get("tags", {})
    parse = src.get("stages", {}).get("parse", {})
    review = src.get("stages", {}).get("review", {})
    md = module.md_path(src)
    q = mcq = written = ""
    if md.exists() and src.get("status") != "excluded":
        text = md.read_text(encoding="utf-8")
        q = len(re.findall(r"^### Q\d+", text, re.M))
        answers = re.findall(r"^\*\*Correct Answer:\*\*\s*(\S+)", text, re.M)
        written = sum(1 for a in answers if a == "-")
        mcq = q - written
    sources = parse.get("sources") or {}
    provenance = " / ".join(f"{k} {v}" for k, v in sorted(sources.items())) if sources else ""
    if src.get("status") == "excluded":
        status = f"EXCLUDED — {src.get('exclusion')}"
    elif review.get("spot_check"):
        status = f"REVIEWED — spot-check {review['spot_check']}"
    else:
        status = src.get("status", "pending").upper()
    return [src["nn"], f"`{Path(src['rel']).name}`", f"{t.get('class', '')} · {src.get('pages') or ''} p",
            f"`{src['md']}`", str(q), str(mcq), str(written), provenance,
            tags.get("tag") or "", tags.get("tagSuggere") or "None", str(tags.get("year") or ""), status]


def render(module: Module, state: dict[str, Any]) -> str:
    rows = state["sources"]
    live = [s for s in rows if s.get("status") != "excluded"]
    head = ["# " + module.name + " — source inventory and extraction catalog", "",
            f"> Generated by `mbset.py catalog` on {now()[:10]} from `.mbset/state.json` — do not edit by hand.", "",
            f"- Sources: **{len(rows)}** (live {len(live)}, excluded {len(rows) - len(live)})",
            f"- Archives expanded: **{len(state.get('archives', []))}**", ""]
    table = ["| # | Source | Type | Markdown | Q | MCQ | QROC | Answer sources | Tag | tagSuggere | Year | Status |",
             "|---|---|---|---|---:|---:|---:|---|---|---|---|---|"]
    table += ["| " + " | ".join(_row(module, s)) + " |" for s in rows]
    return "\n".join(head + table) + "\n"


def write(module: Module, state: dict[str, Any]) -> Path:
    module.markdown.mkdir(exist_ok=True)
    path = module.markdown / "00_CATALOG_OF_ALL_FILES.md"
    if path.exists() and not state.get("catalog_managed"):
        backup = module.meta / "work" / "backup" / f"00_CATALOG_OF_ALL_FILES.{now().replace(':', '')}.md"
        backup.parent.mkdir(parents=True, exist_ok=True)
        backup.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    path.write_text(render(module, state), encoding="utf-8")
    state["catalog_managed"] = True
    module.save(state)
    return path


def tag_map(module: Module, state: dict[str, Any]) -> Path:
    data = {}
    for s in state["sources"]:
        tags = s.get("tags", {})
        if s.get("status") == "excluded":
            continue
        data[s["md"]] = {"Tag": tags.get("tag"), "tagSuggere": tags.get("tagSuggere"), "Year": tags.get("year")}
    path = module.meta / "tag_map.json"
    dump_json(path, data)
    return path


# --------------------------------------------------------------------------- packets
def packet_groups(state: dict[str, Any], n: int) -> tuple[list[list[dict[str, Any]]], list[int]]:
    """Pending sources in n bins balanced by page count (greedy, largest first). Deterministic, so
    `packets` and the brief writer always agree on which NN is in which packet."""
    todo = [s for s in state["sources"] if s.get("status") not in ("excluded", "reviewed", "missing")]
    todo.sort(key=lambda s: -(s.get("pages") or 1))
    bins: list[list[dict[str, Any]]] = [[] for _ in range(max(n, 1))]
    load = [0] * len(bins)
    for s in todo:  # greedy balance by page count
        k = load.index(min(load))
        bins[k].append(s)
        load[k] += s.get("pages") or 1
    return bins, load


def packets(module: Module, state: dict[str, Any], n: int, script: str) -> list[Path]:
    bins, load = packet_groups(state, n)
    out = []
    root = module.root
    for k, group in enumerate(bins, 1):
        if not group:
            continue
        only = ",".join(s["nn"] for s in sorted(group, key=lambda s: s["nn"]))
        lines = [f"# Work packet {k}/{len(bins)} — {module.name}", "",
                 f"Files ({len(group)}, {load[k - 1]} pages): {only}", "",
                 "You own ONLY these sources: their `.mbset/profiles/NN.yaml`, their markdown files and their",
                 "`.mbset/locks/NN.lock`. Never edit the catalog, the Excel, or another packet's files.", "",
                 "## Loop for each file", "", "```bash",
                 f'python {script} lock "{root}" {only}',
                 f'python {script} parse "{root}" --only NN          # profile → markdown + flags',
                 f'python {script} show "{root}" NN --flags          # read only the flagged questions',
                 "# fix the profile and re-parse, or fix single questions:",
                 f'python {script} fix "{root}" NN --drop 7 --reason "…"',
                 f'python {script} answersheet "{root}" --only NN    # unanswered MCQs: view the sheets, read the marks',
                 f'python {script} fix "{root}" NN --answers "3=B 4=D 9=A" --source marked',
                 f'python {script} fix "{root}" NN --exp-file answers.json   # written: model answers (derived)',
                 f'python {script} figures "{root}" --only NN        # if figure-dependent questions exist',
                 f'python {script} spotcheck "{root}" --only NN      # view the PNG sheets it prints',
                 f'python {script} review "{root}" NN --spot "6/6 OK"',
                 f'python {script} check "{root}" --only NN          # must print 0 hard failures',
                 "```", "", "| NN | source | class | pages |", "|---|---|---|---:|"]
        lines += [f"| {s['nn']} | {Path(s['rel']).name} | {s.get('triage', {}).get('class')} | {s.get('pages')} |"
                  for s in sorted(group, key=lambda s: s["nn"])]
        path = module.meta / "packets" / f"packet_{k}.md"
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        out.append(path)
    return out


def lock(module: Module, nns: list[str], owner: str) -> list[str]:
    taken = []
    for nn in nns:
        path = module.meta / "locks" / f"{nn}.lock"
        if path.exists() and path.read_text(encoding="utf-8").split("\n")[0] != owner:
            taken.append(f"{nn} (held by {path.read_text(encoding='utf-8').splitlines()[0]})")
            continue
        path.write_text(f"{owner}\n{now()}\n", encoding="utf-8")
    return taken


def unlock(module: Module, nns: list[str]) -> None:
    for nn in nns:
        (module.meta / "locks" / f"{nn}.lock").unlink(missing_ok=True)


def excel_path(module: Module) -> Path:
    return module.root / f"{module.name}_Questions.xlsx"


def category(module: Module, state: dict[str, Any]) -> tuple[str | None, str | None]:
    if state.get("category_id"):
        return state["category_id"], state.get("category_name")
    try:
        import openpyxl
    except ImportError:
        return None, None
    exports = sorted(module.root.glob("subcategories_*_20*.xlsx"))
    for x in reversed(exports):
        ws = openpyxl.load_workbook(x, read_only=True).active
        rows = ws.iter_rows(values_only=True)
        header = [str(h or "") for h in next(rows)]
        if "categoryId" in header:
            for row in rows:
                cid = row[header.index("categoryId")]
                name = row[header.index("categoryName")] if "categoryName" in header else None
                if cid:
                    return str(cid), str(name) if name else None
    return None, None


# --------------------------------------------------------------------------- worker briefs
def repo_root(path: Path) -> Path:
    """The git work tree that holds the module (a relay's --cd); the module itself if there is none."""
    for p in [path, *path.parents]:
        if (p / ".git").exists():
            return p
    return path


def packet_brief(module: Module, k: int, total: int, group: list[dict[str, Any]], pages: int,
                 script: str, repo: Path | None = None) -> str:
    """A self-contained brief for one worker (whichever the user chose): it sees nothing but this text."""
    repo = repo or repo_root(module.root)
    nns = ",".join(s["nn"] for s in sorted(group, key=lambda s: s["nn"]))
    M, S, owner = str(module.root), script, f"packet_{k}"
    rows = [f"| {s['nn']} | {Path(s['rel']).name} | {s.get('triage', {}).get('class', '?')} | "
            f"{s.get('pages') or ''} | Markdown_Questions/{s['md']} |" for s in sorted(group, key=lambda s: s["nn"])]
    return "\n".join([
        f"# MBset review packet {k}/{total} — {module.name}",
        "",
        "You are a worker on the MBset medical question-bank pipeline. This brief is everything you get:",
        "there is no chat history, no other instructions and no skill file. Follow it exactly. Do NOT commit.",
        "",
        "## Context",
        f"- Repository (your working root): {repo}",
        f"- Module folder: {M}",
        f"- Pipeline CLI: {S}   (run it as `python3 {S} <command> \"{M}\" …`)",
        f"- Your sources (NN list): {nns}   — {len(group)} file(s), {pages} page(s)",
        "- Every source was already inventoried, OCRed and parsed by a deterministic parser. The parser, not",
        "  you, writes each question's text into `Markdown_Questions/NN_*.md`. Your job is judgement on",
        "  what it flags: flag triage, making every question complete and clean against the page image,",
        "  reading pen marks on answer sheets, spot checks, QROC model answers.",
        "- The PNG sheets the commands print (answer sheets, spot-check sheets, contact sheets) are images:",
        "  open each one with your image-viewing tool and read it; never guess what is on it.",
        "",
        "| NN | source file | class | pages | markdown |",
        "|---|---|---|---:|---|",
        *rows,
        "",
        "## Loop (run for each NN of yours, in order)",
        "```bash",
        f'S={S}',
        f'M="{M}"',
        f'python3 $S lock "$M" {nns} --owner {owner}        # refuses sources held by someone else',
        'python3 $S parse "$M" --only NN                    # profile → markdown + flags',
        'python3 $S show "$M" NN --flags                    # read only the flagged questions',
        'python3 $S show "$M" NN --dropped                  # the noise filter must not have eaten a question',
        '#   profile problem → edit $M/.mbset/profiles/NN.yaml, then parse --only NN again',
        'python3 $S fix "$M" NN --drop 7 --reason "…"       # single questions (also --image N=Images/NN_QN.png)',
        'python3 $S fix "$M" NN --text-file t.json          # stem/options re-read from the page, exactly as printed',
        '#   a scan that loses questions: profile `ocr: {tool: paddle, dpi: 200}`, then `ocr --only NN --force`',
        'python3 $S fix "$M" NN --clear-drops ocr           # after an OCR/profile change: OCR-garbled drops come back',
        'python3 $S answersheet "$M" --only NN              # unanswered MCQs: view the PNGs, read the marks',
        'python3 $S fix "$M" NN --answers "3=B 4=D" --source marked       # only marks you can see; else leave ?',
        'python3 $S fix "$M" NN --answers "9=C" --source derived          # only when the source has no answer',
        'python3 $S fix "$M" NN --exp-file answers.json     # QROC model answers {"N": "…"} (derived)',
        'python3 $S figures "$M" --only NN                  # if figure-dependent questions exist',
        'python3 $S spotcheck "$M" --only NN                # view the PNG sheets it prints',
        'python3 $S review "$M" NN --spot "6/6 OK"          # your verdict on the spot-check sheets',
        f'python3 $S check "$M" --only {nns}                 # must print 0 hard failures',
        f'python3 $S lock "$M" {nns} --release',
        "```",
        "",
        "## Rules (hard)",
        f"1. Only touch files of your NNs ({nns}): `.mbset/profiles/NN.yaml`, `Markdown_Questions/NN_*.md`,",
        "   `Images/NN_*`, and their state through `fix` / `review` / `set`. Never edit another NN, the catalog",
        "   (`00_CATALOG_OF_ALL_FILES.md`), the tag map, any Excel file, or the pipeline code.",
        "2. Every question must be complete and clean, exactly as printed: all options present, no OCR",
        "   symbols (`¢ © ® | ~ @`), words in the printed order, stem and options not glued together.",
        "   Whole-file problems: fix the profile and re-parse (try `ocr.tool: paddle` for bad scans; after an",
        "   OCR change run `fix NN --clear-drops ocr`). Single questions: open the page image and write",
        "   what is printed with `fix NN --text-file t.json` ({\"7\": {\"stem\": …, \"options\": {\"C\": …},",
        "   \"note\": …}}). Copy the printed words exactly — never paraphrase, shorten, reword, complete",
        "   from knowledge or copy from another file. A question you cannot read on the page is dropped",
        "   with reason `UNREADABLE p<page>: …`, never guessed.",
        "3. `fix --answers … --source marked` ONLY when the mark is visible on the sheet. If you are not sure,",
        "   leave that answer `?` and list it as unresolved. Never guess, never copy an answer from a similar",
        "   question in another file, never default to A.",
        "4. Answers from your own medical knowledge ONLY via `--source derived` (MCQ, and only when the source",
        "   gives no answer) or `--exp-file` (QROC model answers, recorded as derived). List every one.",
        "5. Keep Arabic characters out of everything you write (model answers included).",
        "6. Do not run `catalog`, `build`, `packets` or `renumber`, and do not commit or push.",
        f"7. Finish with `python3 $S check \"$M\" --only {nns}`; report its summary line as printed.",
        "",
        "## Report contract (your final message, nothing else)",
        "- Per file: `NN | questions | MCQ | QROC | answered | check: OK/FAIL`.",
        "- Per file answer-source counts: key / marked / online / derived / ? (unanswered).",
        "- Derived list: every derived answer and model answer as `NN Qn` (letter or \"model answer\").",
        "- Unresolved: every flag you could not resolve and every `?` answer, with the reason.",
        "- Profile changes: which NN.yaml fields you changed and why; drops with their reasons.",
        "- Text fixes: count per file and the question numbers (`NN: Q3, Q7 …`).",
        f"- The final `check --only {nns}` summary lines (hard failures / review items).",
        "",
    ])
