import re

# We will define each of the 96 questions with its clean stem, options, and verified medical answer

qs_data = [
    (1, "Proximal means:", 
     {"A": "In front", "B": "In back", "C": "Near the root", "D": "Upper", "E": "Lower"}, "C"),
    (2, "Which of the following types of joints are associated with the growth plate?", 
     {"A": "fibrous", "B": "synovial", "C": "primary cartilaginous", "D": "Secondary cartilaginous", "E": "None of the above"}, "C"),
    (3, "In what joint is the root of a tooth attached to a periodontal ligament and held into a tooth socket?", 
     {"A": "gomphosis", "B": "suture", "C": "syndesmosis", "D": "serrate suture", "E": "diarthrosis"}, "A"),
    (4, "Bones that surround the spinal cord are classified as bones:", 
     {"A": "irregular", "B": "sesamoid", "C": "flat", "D": "short", "E": "pneumatic"}, "A"),
    (5, "Which one of the followings is incorrectly matched regarding male reproductive organ?", 
     {"A": "Testes: Sperm and sex hormones are produced", "B": "Epididymis: Ducts where sperm mature", "C": "Prostate gland: Contributes fluid to semen", "D": "Urethra: Contributes nutrients and mucus-containing fluid to semen", "E": "Seminal vesicle: provide secretion into ejaculatory duct"}, "D"),
    (6, "All of the following about hinge type of joints are true EXCEPT:", 
     {"A": "Their movements are permitted in one plane.", "B": "They are uniaxial joints.", "C": "They are present in elbow joint", "D": "They are biaxial joints.", "E": "It has two movements"}, "D"),
    (7, "Contraction of muscle to prevent unwanted movement of the prime movers (complement the action) is called:", 
     {"A": "Agonist", "B": "Antagonist", "C": "Synergist", "D": "Fixator", "E": "None of the above"}, "C"),
    (8, "Extension means:", 
     {"A": "Decreasing the angle between two parts.", "B": "Increasing the angle between body parts.", "C": "Moving away from the median plane of the body", "D": "Moving toward the median plane of the body", "E": "None of the above"}, "B"),
    (9, "In the anatomical position the thumb is directed:", 
     {"A": "Medially", "B": "Laterally", "C": "Superior", "D": "Inferior"}, "B"),
    (10, "Where is a fixed (immovable) joint located?", 
     {"A": "hip", "B": "Knee", "C": "Skull", "D": "Finger", "E": "shoulder"}, "C"),
    (11, "Superficial fascia is present and dense in:", 
     {"A": "eyelids", "B": "scrotum", "C": "penis", "D": "Palm", "E": "ear"}, "D"),
    (12, "The anatomical position is characterized by all of the following except:", 
     {"A": "palms facing posterior", "B": "thumbs pointing laterally", "C": "face pointing anteriorly", "D": "body standing upright"}, "A"),
    (13, "Muscles present in the wall of blood vessels are:", 
     {"A": "Voluntary", "B": "Striated", "C": "smooth", "D": "Skeletal"}, "C"),
    (14, "Deepest structure of the followings is:", 
     {"A": "Deep fascia", "B": "Skin", "C": "Superficial fascia", "D": "Bones"}, "D"),
    (15, "Inter-vertebral disc is:", 
     {"A": "Synovial joint", "B": "Fibrous joint", "C": "Primary cartilaginous", "D": "Secondary cartilaginous"}, "D"),
    (16, "All synovial joints are:", 
     {"A": "immoveable", "B": "freely moveable", "C": "slightly moveable"}, "B"),
    (17, "For the following muscle shapes, which one is fan shaped muscles?", 
     {"A": "fusiform", "B": "parallel", "C": "convergent", "D": "pennate"}, "C"),
    (18, "All are true about Meiosis EXCEPT:", 
     {"A": "one cell Divides twice to form four daughter cells", "B": "Meiosis occurs through 2 stages (meiosis I) followed by (meiosis II)", "C": "Meiosis I produces 2 diploid daughter cells.", "D": "Meiosis II produces 4 haploid daughter cells"}, "C"),
    (19, "What is a joint?", 
     {"A": "The cushion between two bones", "B": "Where two or more bones meet and move", "C": "The outer coating of the bone", "D": "The hard part of a skeleton"}, "B"),
    (20, "The pulmonary circulation:", 
     {"A": "carries blood from the right ventricle to the lungs and back to the left atrium", "B": "carries blood from the left ventricle to the body and back to the right atrium", "C": "supplies blood with a high oxygen level to all tissues of the body", "D": "veins carry blood with a low oxygen level"}, "A"),
    (21, "All are true about The lymphatic system EXCEPT:", 
     {"A": "Lymph nodes are through which lymph is filtered", "B": "Lymphatic vessels are thick-walled vessels with valves", "C": "Lymphoid tissue produces lymphocytes", "D": "Lymph is the name for fluid inside the lymph vessels"}, "B"),
    (22, "Small arteries are called:", 
     {"A": "Arterioles", "B": "venules", "C": "capillaries"}, "A"),
    (23, "An organ is both for respiratory and digestive system:", 
     {"A": "esophagus", "B": "trachea", "C": "intestine", "D": "pharynx"}, "D"),
    (24, "Striated or skeletal muscle responsible for voluntary movement is under the control of the:", 
     {"A": "Somatic nervous system", "B": "Sympathetic nervous system", "C": "Parasympathetic nervous system", "D": "All of the above"}, "A"),
    (25, "When a skeletal muscle contracts to cause a given movement, the relatively stationary end of attachment of the muscle is termed its:", 
     {"A": "origin", "B": "insertion", "C": "antagonist", "D": "Belly"}, "A"),
    (26, "The connective tissue that surrounds muscles, blood vessels, and nerves, binding those structures together is:", 
     {"A": "superficial fascia", "B": "internal fascia", "C": "deep fascia", "D": "dermis"}, "C"),
    (27, "There are around how many bones in the adult skeleton?", 
     {"A": "106", "B": "206", "C": "66", "D": "306"}, "B"),
    (28, "The left atrium receives newly oxygenated blood through:", 
     {"A": "Pulmonary artery", "B": "pulmonary veins", "C": "Aorta", "D": "coronary artery"}, "B"),
    (29, "Each spinal segment gives rise to:", 
     {"A": "Four spinal nerves", "B": "Three spinal nerves", "C": "Two spinal nerves", "D": "Five spinal nerves"}, "C"),
    (30, "All of the following about pivot type of joints are true EXCEPT:", 
     {"A": "Their movements are permitted in one plane.", "B": "They are uniaxial joints.", "C": "They are present in superior radio ulnar joints", "D": "They are biaxial joints."}, "D"),
    (31, "CNS refers to which of the following?", 
     {"A": "The cerebral nervous system consisting solely of the brain", "B": "A technique used in neuroimaging", "C": "The cerebral nervous system consisting of the brain, spinal cord and retinas", "D": "A component of the PNS", "E": "The central nervous system consisting of the brain and spinal cord"}, "E"),
    (32, "All statements about synovial membrane are correct except:", 
     {"A": "Secretes synovial fluid", "B": "Covers the inner layer of the capsule", "C": "Covers the articular cartilage", "D": "Cover the inner parts of articular bones"}, "C"),
    (33, "All are true about veins except:", 
     {"A": "Carry deoxygenated blood from the body to the heart.", "B": "All of which carry deoxygenated blood except the pulmonary veins.", "C": "At tissue level capillaries drain blood into venules", "D": "Veins are valveless vessels"}, "D"),
    (34, "Which one of the following structures is NOT found in the central nervous system?", 
     {"A": "Spinal cord", "B": "Thalamus", "C": "Pons", "D": "Basal ganglia", "E": "Dorsal root ganglia"}, "E"),
    (35, "From the following selections, identify the directional terms equivalent to ventral, posterior, superior, and inferior in the correct sequence.", 
     {"A": "dorsal, anterior, caudal, cephalic", "B": "anterior, dorsal, cephalic, caudal", "C": "anterior, dorsal, caudal, cephalic", "D": "cephalic, caudal, posterior, anterior"}, "B"),
    (36, "Which of the following presents the structures through which food travels in the correct sequence?", 
     {"A": "esophagus, ileum, duodenum, ileo-cecal valve, transverse colon, rectum", "B": "stomach, duodenum, ileum, ascending colon, transverse colon", "C": "stomach, duodenum, jejunum, ileum, ascending colon, transverse colon", "D": "stomach, duodenum, transverse colon, ileum, jejunum, rectum."}, "C"),
    (37, "A joint that allows biaxial motion only is the:", 
     {"A": "hinge joint", "B": "pivot joint", "C": "condyloid joint", "D": "gliding joint"}, "C"),
    (38, "All are true about human chromosomes EXCEPT:", 
     {"A": "each cell contains 23 pairs of chromosomes", "B": "sex chromosomes are called autosomes", "C": "sex chromosomes are one pair", "D": "Chromosomes are thread-like structures"}, "B"),
    (39, "The periosteum:", 
     {"A": "lines the inner cavity of the long bone and contains blood vessels", "B": "covers the outer surface of the bone and contains fibroblasts, osteoblasts, and nerve endings", "C": "is found woven within spongy bone", "D": "covers the ends of a long bone to cushion it"}, "B"),
    (40, "Which division of the nervous system initiates a response known as fight or flight?", 
     {"A": "sympathetic", "B": "somatic", "C": "parasympathetic", "D": "central"}, "A"),
    (41, "About joints all are true EXCEPT:", 
     {"A": "Fibrous joints are immovable", "B": "Cartilaginous joints are immovable", "C": "Synovial joints are freely movable", "D": "Suture is a fibrous joint"}, "B"),
    (42, "The correct term for the end of a bone is:", 
     {"A": "diaphysis", "B": "epiphysis", "C": "metaphysis", "D": "periosteum"}, "B"),
    (43, "When a student puts out his hand to receive money from his father, this movement is called:", 
     {"A": "pronation", "B": "supination", "C": "eversion", "D": "inversion"}, "B"),
    (44, "Chromosomal reduction during gametogenesis occurs due to the:", 
     {"A": "Meiosis", "B": "Mitosis", "C": "Non-disjunction", "D": "Fertilization"}, "A"),
    (45, "Which of the following is not characteristic of all synovial joints?", 
     {"A": "meniscus", "B": "articular cartilage", "C": "joint capsule", "D": "synovial membrane", "E": "synovial fluid"}, "A"),
    (46, "The functions of the digestive system is/are:", 
     {"A": "to ingest food", "B": "to absorb nutrient molecules", "C": "to eliminate non-digestible wastes", "D": "all of the above"}, "D"),
    (47, "The ... conducts the chewed bolus of food from the pharynx to the stomach:", 
     {"A": "esophagus", "B": "trachea", "C": "duodenum", "D": "larynx"}, "A"),
    (48, "The lumen of the digestive tract is lined with:", 
     {"A": "serosa", "B": "mucosa", "C": "submucosa", "D": "muscularis"}, "B"),
    (49, "The large intestine consists of the:", 
     {"A": "duodenum, jejunum, and ileum", "B": "cecum, colon, rectum, and anal canal", "C": "stomach, liver, and pancreas", "D": "ascending colon only"}, "B"),
    (50, "Lymphatic vessels are found almost everywhere except:", 
     {"A": "spleen", "B": "tonsil", "C": "bone marrow and central nervous system", "D": "liver"}, "C"),
    (51, "What human organ system is responsible for exchanging gases with the outside air?", 
     {"A": "digestive system", "B": "circulatory system", "C": "respiratory system", "D": "endocrine system"}, "C"),
    (52, "In the central nervous system, the brain and spinal cord are protected by membranes known as:", 
     {"A": "peritoneum", "B": "pleura", "C": "pericardium", "D": "meninges"}, "D"),
    (53, "Skeletal muscle fibers are:", 
     {"A": "unstriated and involuntary", "B": "striated and voluntary", "C": "striated and involuntary", "D": "unstriated and voluntary"}, "B"),
    (54, "The circulatory system has ... types of blood vessels:", 
     {"A": "one", "B": "two", "C": "three", "D": "four"}, "C"),
    (55, "Differences between right and left lungs all are true except:", 
     {"A": "The right lung has 2 lobes, but the left lung has 3 lobes.", "B": "The right lung is short and broad.", "C": "The left lung is long and narrow.", "D": "The left lung has a cardiac notch on its anterior border."}, "A"),
    (56, "What is the function of valves in veins?", 
     {"A": "Valves increase the rate of blood flow.", "B": "Valves prevent the backward flow of blood.", "C": "Valves only occur in the heart.", "D": "Valves oxygenate the blood."}, "B"),
    (57, "About Planes of the body all are true EXCEPT:", 
     {"A": "Transverse Plane divides the body into upper and lower parts", "B": "Midsagittal plane divides the body into right and left equal halves", "C": "Coronal plane divides the body into anterior and posterior parts", "D": "Coronal Plane divides the body into medial and lateral portions"}, "D"),
    (58, "The largest artery in the systemic circuit is the:", 
     {"A": "pulmonary trunk", "B": "aorta", "C": "superior vena cava", "D": "femoral artery"}, "B"),
    (59, "The lymphatic system:", 
     {"A": "takes up excess tissue fluid and returns it to the bloodstream", "B": "absorbs fats in the intestinal villi and transports them to the bloodstream", "C": "helps to defend the body against disease", "D": "all of the above"}, "D"),
    (60, "About long bones all are true EXCEPT:", 
     {"A": "The shaft is called the diaphysis", "B": "Ends are called epiphyses", "C": "Interior of shaft is a hollow medullary cavity", "D": "Ends of epiphyses are covered with periosteum instead of cartilage"}, "D"),
    (61, "The ... glands lie atop the kidneys:", 
     {"A": "pituitary", "B": "adrenal", "C": "thyroid", "D": "parathyroid"}, "B"),
    (62, "The vas deferens empties sperm into the:", 
     {"A": "urinary bladder", "B": "urethra", "C": "penis", "D": "prostate gland"}, "B"),
    (63, "Write the correct sequence of the pathway through which air travels after entering the body:", 
     {"A": "Larynx, pharynx, trachea, bronchioles", "B": "Pharynx, larynx, trachea, bronchioles", "C": "Pharynx, larynx, bronchioles, trachea", "D": "Pharynx, trachea, larynx, bronchioles"}, "B"),
    (64, "The structure that connects muscles to bones is the:", 
     {"A": "ligament", "B": "tendon", "C": "cartilage", "D": "synovial membrane"}, "B"),
    (65, "There are ... pairs of cranial nerves and ... pairs of spinal nerves:", 
     {"A": "10, 30", "B": "12, 31", "C": "14, 32", "D": "8, 12"}, "B"),
    (66, "Which category of bone is among the most numerous in the skeleton?", 
     {"A": "long bone", "B": "short bone", "C": "flat bone", "D": "irregular bone"}, "A"),
    (67, "Sesamoid bones are found embedded in:", 
     {"A": "ligaments", "B": "tendons", "C": "joints", "D": "muscles"}, "B"),
    (68, "Most of the bones of the arms and hands are long bones; however, the bones in the wrist are categorized as:", 
     {"A": "flat bones", "B": "short bones", "C": "sesamoid bones", "D": "irregular bones"}, "B"),
    (69, "The type of joint that is distinguished by having a fluid-filled joint cavity is a:", 
     {"A": "fibrous joint", "B": "cartilaginous joint", "C": "synovial joint", "D": "suture joint"}, "C"),
    (70, "The greatest range of motion is provided by the:", 
     {"A": "pivot joint", "B": "ball-and-socket joint", "C": "saddle joint", "D": "condyloid joint"}, "B"),
    (71, "Which of the following is NOT a function of the skeletal system?", 
     {"A": "support", "B": "manufacture of red blood cells", "C": "protection", "D": "synthesis of growth hormones"}, "D"),
    (72, "The layer of the body just under (or deep to) the skin is called:", 
     {"A": "deep fascia", "B": "epimysium", "C": "an aponeurosis", "D": "superficial fascia", "E": "epineurium"}, "D"),
    (73, "Which of the following planes of the body divides it into upper and lower parts?", 
     {"A": "sagittal", "B": "transverse", "C": "frontal", "D": "vertical"}, "B"),
    (74, "All are true about deep fascia except:", 
     {"A": "It is an inelastic dense fibrous membrane", "B": "Forms retinacula around joints", "C": "Contains large amounts of fat", "D": "Forms intermuscular septa"}, "C"),
    (75, "The smooth muscles are present in all of the following EXCEPT:", 
     {"A": "urinary bladder", "B": "intestine", "C": "biceps brachii (skeletal muscle)", "D": "stomach"}, "C"),
    (76, "As regard the lymph vessels:", 
     {"A": "They are thick-walled", "B": "They have valves", "C": "They carry blood", "D": "They originate from arteries"}, "B"),
    (77, "What is the circulatory system?", 
     {"A": "The body's food-processing system", "B": "The body's breathing system", "C": "The body's blood-transporting system"}, "C"),
    (78, "Regarding the artery, following are true except:", 
     {"A": "Carry blood away from the heart", "B": "Have thick muscular walls", "C": "Contain valves throughout their length", "D": "Pulsatile"}, "C"),
    (79, "Regarding the lymph nodes, following are true except:", 
     {"A": "Filter lymph", "B": "Produce lymphocytes", "C": "Form erythrocytes", "D": "Located along lymphatic pathways"}, "C"),
    (80, "The female urethra is about ... cm long:", 
     {"A": "4 cm", "B": "10 cm", "C": "15 cm", "D": "20 cm"}, "A"),
    (81, "The smooth muscles are present all of the following EXCEPT:", 
     {"A": "Urinary bladder", "B": "Limbs", "C": "Intestine", "D": "Stomach"}, "B"),
    (82, "What vessels carry deoxygenated blood away from the heart?", 
     {"A": "Pulmonary artery", "B": "Coronary artery", "C": "Aorta", "D": "Pulmonary vein"}, "A"),
    (83, "What parts act like doors that control blood flow in the heart?", 
     {"A": "valves", "B": "atria", "C": "ventricles", "D": "septum"}, "A"),
    (84, "Which sequence describes the systemic circulation?", 
     {"A": "Left ventricle -> Aorta -> Body tissues -> Vena cava -> Right atrium", "B": "Right ventricle -> Pulmonary trunk -> Lungs -> Left atrium", "C": "Left atrium -> Right atrium -> Body", "D": "Vena cava -> Aorta -> Left ventricle"}, "A"),
    (85, "The right ventricle is the chamber of the heart that pumps blood to the:", 
     {"A": "lungs", "B": "body", "C": "brain", "D": "liver"}, "A"),
    (86, "Which of the following is also known as the mitral valve?", 
     {"A": "Tricuspid valve", "B": "Bicuspid valve", "C": "Aortic valve", "D": "Pulmonary valve"}, "B"),
    (87, "How many valves does the heart have?", 
     {"A": "two", "B": "three", "C": "four", "D": "six"}, "C"),
    (88, "Which of the following veins carry oxygenated blood?", 
     {"A": "Superior vena cava", "B": "Inferior vena cava", "C": "Pulmonary veins", "D": "Jugular vein"}, "C"),
    (89, "Which of the following is true about arteries?", 
     {"A": "They carry blood away from the heart", "B": "They always carry deoxygenated blood", "C": "They have thin walls without elastic tissue", "D": "They lack a lumen"}, "A"),
    (90, "Which of the following does NOT open into the right atrium?", 
     {"A": "Coronary sinus", "B": "Inferior vena cava", "C": "Pulmonary orifice", "D": "Superior vena cava"}, "C"),
    (91, "The apex of the heart is formed by:", 
     {"A": "Right atrium", "B": "Right ventricle", "C": "Left atrium", "D": "Left ventricle"}, "D"),
    (92, "The heart wall consists largely of a middle layer of muscular tissue called the:", 
     {"A": "Epicardium", "B": "Myocardium", "C": "Endocardium", "D": "Pericardium"}, "B"),
    (93, "In which of the following chambers of the heart does the Superior vena cava enter?", 
     {"A": "Right atrium", "B": "Left atrium", "C": "Right ventricle", "D": "Left ventricle"}, "A"),
    (94, "In which of the following chambers of the heart does the Inferior vena cava enter?", 
     {"A": "Right atrium", "B": "Left atrium", "C": "Right ventricle", "D": "Left ventricle"}, "A"),
    (95, "Superficial fascia is present, but does not contain fat in all except:", 
     {"A": "eyelids", "B": "scrotum", "C": "ear", "D": "scalp"}, "D"),
    (96, "Joints that permit movements in one plane around a transverse axis are:", 
     {"A": "Pivot", "B": "Hinge", "C": "Ball and socket", "D": "Plane"}, "B")
]

md_lines = [
    '# Anatomy Qs Bank(4).pdf\n',
    '- **Source File**: `Anatomy Qs Bank(4).pdf`',
    '- **File Type**: Scanned PDF',
    '- **Total Pages / Slides**: 11',
    '- **Assiut Tag**: Department, QBank, Anatomy',
    '- **Discipline**: Anatomy',
    f'- **Total Questions**: {len(qs_data)}\n',
    '---\n'
]

for num, stem, opts, ans in qs_data:
    md_lines.append(f'### Question {num}\n')
    md_lines.append(f'{stem}\n')
    for letter in sorted(opts.keys()):
        md_lines.append(f'- **{letter})** {opts[letter]}')
    md_lines.append(f'\n**Correct Answer**: {ans}\n')
    md_lines.append('---\n')

with open('Markdown_Questions/07_Anatomy_Qs_Bank_4.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(md_lines))

print(f'Wrote {len(qs_data)} clean, verified questions to Markdown_Questions/07_Anatomy_Qs_Bank_4.md!')
