#!/usr/bin/env python3
"""Curate the Assiut NEU213 Final Exam (Form B), dated 13 January 2022."""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
from lib_md import Question, write_markdown  # noqa: E402


MODULE = SCRIPT_DIR.parent
OUTPUT = MODULE / "Markdown_Questions" / "06_Final_2022.md"
TAG = "Exams, Final 2022"


def written(stem: str, answer: str, discipline: str) -> Question:
    return Question(stem=stem, correct="-", source="derived", exp=answer,
                    tag=TAG, tag_suggere=discipline, year=2022)


def mcq(stem: str, options: list[str], answer: str) -> Question:
    return Question(
        stem=stem,
        options=options,
        correct=answer,
        source="derived",
        exp="No legible printed MCQ key is present in the scan; the answer was derived from the source wording and standard neuroscience content and requires final spot-check.",
        tag=TAG,
        year=2022,
    )


WRITTEN = [
    # Question I: Pharmacology.
    written("Compare typical and atypical antipsychotics regarding uses and adverse effects.",
            "Typical antipsychotics are used mainly for positive psychotic symptoms and commonly cause extrapyramidal symptoms, hyperprolactinemia, and tardive dyskinesia. Atypical antipsychotics treat positive and negative symptoms and have a lower extrapyramidal risk but may cause weight gain, diabetes, dyslipidemia, and other metabolic effects. Clozapine may cause agranulocytosis and myocarditis.", "Pharmacology"),
    written("Enumerate two therapeutic uses and two common adverse effects of benzodiazepines.",
            "Therapeutic uses include anxiety disorders, insomnia, status epilepticus, muscle spasm, and alcohol withdrawal. Common adverse effects include sedation, impaired coordination, anterograde amnesia, tolerance, dependence, and respiratory depression when combined with other depressants.", "Pharmacology"),
    written("Enumerate one method to control the long-term side effects of levodopa and carbidopa.",
            "Use the lowest effective dose, divide the doses, or add a dopamine agonist or a COMT inhibitor and reduce levodopa exposure. Drug holidays may be used selectively under specialist supervision, but abrupt withdrawal should be avoided.", "Pharmacology"),
    written("Write about two different mechanisms of action of antiepileptic drugs with one example for each.",
            "Examples include blockade of voltage-gated sodium channels by phenytoin or carbamazepine, enhancement of GABA-mediated inhibition by benzodiazepines or phenobarbital, blockade of T-type calcium channels by ethosuximide, and reduction of glutamatergic transmission by drugs such as felbamate. Any two mechanisms with examples are acceptable.", "Pharmacology"),
    # Question II: Anatomy.
    written("All muscles of the palate are innervated by the cranial part of the accessory nerve through a pharyngeal branch of the vagus nerve. Which palatal muscle is not supplied by this group?",
            "Tensor veli palatini, which is supplied by the mandibular division of the trigeminal nerve through the nerve to medial pterygoid.", "Anatomy"),
    written("What are the actions of the sternocleidomastoid muscle?",
            "Unilateral contraction laterally flexes the neck to the same side and rotates the face to the opposite side. Bilateral contraction flexes the neck and can extend the head at the atlanto-occipital joints. It can also act as an accessory muscle of inspiration.", "Anatomy"),
    written("What are the two terminal branches of the external carotid artery?",
            "The superficial temporal artery and the maxillary artery.", "Anatomy"),
    written("Define dermatome.",
            "A dermatome is an area of skin supplied by sensory fibers from one spinal nerve root.", "Anatomy"),
    written("The corticobulbar tract supplies all motor cranial nerve nuclei bilaterally except which nuclei?",
            "The lower part of the facial motor nucleus and the hypoglossal nucleus, especially the genioglossus component, receive predominantly contralateral corticobulbar input.", "Anatomy"),
    written("Name two nuclei of the vagus nerve in the medulla oblongata.",
            "The dorsal motor nucleus of the vagus and the nucleus ambiguus. The nucleus of the solitary tract is also functionally related to vagal afferents.", "Anatomy"),
    written("What are the nerves that form the cervical plexus?",
            "The anterior rami of C1 to C4 spinal nerves form the cervical plexus. Its branches include the ansa cervicalis, phrenic nerve, lesser occipital, great auricular, transverse cervical, and supraclavicular nerves.", "Anatomy"),
    written("A medulloblastoma in the fourth ventricle presses on the facial colliculus. Which nucleus may be damaged?",
            "The abducens nucleus, which lies deep to the facial colliculus and is looped by facial nerve fibers.", "Anatomy"),
    written("The first pharyngeal cleft develops into what structure?",
            "The external acoustic meatus.", "Anatomy"),
    # Question III: Anatomy.
    written("The auditory radiation is located in which part of the internal capsule?",
            "The sublenticular part of the internal capsule.", "Anatomy"),
    written("Define association fibers and give two examples.",
            "Association fibers connect cortical areas within the same cerebral hemisphere. Examples include the superior longitudinal fasciculus and the uncinate fasciculus; short arcuate fibers are another example.", "Anatomy"),
    written("What artery does not share in the formation of the circle of Willis?",
            "The middle cerebral artery.", "Anatomy"),
    written("Name the tract present within the middle cerebellar peduncle.",
            "Pontocerebellar fibers, also called the transverse pontine fibers, enter the cerebellum through the middle cerebellar peduncle.", "Anatomy"),
    written("Enumerate four derivatives of neural crest cells.",
            "Examples include dorsal root ganglion neurons, autonomic ganglion neurons, Schwann cells, melanocytes, adrenal medullary cells, pia and arachnoid cells, and craniofacial connective tissues. Any four are acceptable.", "Anatomy"),
    written("Name the first neuron in the visual pathway.",
            "The photoreceptor cells of the retina, rods and cones.", "Anatomy"),
    written("Name the first-order neuron in the taste pathway carried by the facial nerve.",
            "The bipolar neurons in the geniculate ganglion of the facial nerve.", "Anatomy"),
    # Question IV: Microbiology.
    written("A country sees childhood paralysis after cessation of live attenuated oral poliovirus vaccine. Name the family of the causative agent.",
            "Picornaviridae.", "Microbiology"),
    written("A patient develops dysphagia and respiratory muscle paralysis after eating homemade strawberry jam. Name the microorganism responsible.",
            "Clostridium botulinum.", "Microbiology"),
    written("An elderly diabetic woman has facial palsy, a perforated tympanic membrane, and greenish ear discharge. Name the most likely causative bacterium.",
            "Pseudomonas aeruginosa.", "Microbiology"),
    # Question V: Pathology.
    written("A 75-year-old man has progressive cognitive deterioration, cortical atrophy, widened sulci, and thin razor-like gyri. What is the most likely diagnosis?",
            "Alzheimer disease.", "Pathology"),
    written("Name two microscopic pathological lesions characteristic of Alzheimer disease.",
            "Neuritic plaques containing beta-amyloid and neurofibrillary tangles containing hyperphosphorylated tau. Granulovacuolar degeneration and cerebral amyloid angiopathy may also occur.", "Pathology"),
    written("Enumerate two other causes of dementia.",
            "Vascular dementia and dementia with Lewy bodies are examples. Frontotemporal dementia and normal-pressure hydrocephalus are other accepted causes.", "Pathology"),
    written("Name two tumors of the peripheral nerves.",
            "Schwannoma and neurofibroma. Malignant peripheral nerve sheath tumor is another example.", "Pathology"),
    # Question VI: Biochemistry.
    written("What is the importance of energy for the brain?",
            "Energy is needed to restore neuronal membrane potentials after depolarization through Na⁺-K⁺ ATPase, to support axonal transport and storage processes, and to synthesize and release neurotransmitters. Glucose and oxygen are therefore essential for continuous brain function.", "Biochemistry"),
    written("Enumerate types of neurotransmitter receptors.",
            "Ionotropic ligand-gated ion-channel receptors and metabotropic G-protein-coupled receptors are the two major types. Other recognized receptor classes include enzyme-linked and intracellular receptors.", "Biochemistry"),
    written("Which glutamate receptor is most often implicated in neuropsychiatric disorders?",
            "The NMDA receptor.", "Biochemistry"),
    # Question VII: Physiology.
    written("Define spatial summation.",
            "Spatial summation is the summation of postsynaptic potentials produced simultaneously at different synapses on a neuron.", "Physiology"),
    written("Define aphasia.",
            "Aphasia is an acquired disorder of language caused by a lesion of the dominant cerebral hemisphere, affecting comprehension, expression, naming, repetition, reading, or writing.", "Physiology"),
    written("Enumerate two functions of the primary auditory cortex.",
            "It receives and analyzes auditory information, including sound intensity, frequency, and localization, and it contributes to conscious perception and discrimination of sounds and speech.", "Physiology"),
    written("Enumerate two functions of the Eustachian tube.",
            "It equalizes air pressure on both sides of the tympanic membrane and drains secretions from the middle ear into the nasopharynx. It also protects the middle ear from nasopharyngeal sound and secretions.", "Physiology"),
    written("Enumerate two functions of the stretch reflex.",
            "It maintains muscle tone and posture and helps resist sudden stretching of a muscle. It also contributes to smooth coordinated movement and tendon-jerk responses.", "Physiology"),
    written("Enumerate two functions of the basal ganglia.",
            "The basal ganglia help initiate and terminate wanted movements, scale their force and direction, inhibit unwanted movements, and participate in procedural motor learning and posture.", "Physiology"),
    written("Discuss two behavioral functions of the hypothalamus, naming the nucleus and its function.",
            "The lateral hypothalamic area promotes feeding, while the ventromedial nucleus promotes satiety. The anterior hypothalamus supports heat loss and parasympathetic responses, whereas the posterior hypothalamus supports heat conservation and sympathetic responses. Any two nucleus-function pairs are acceptable.", "Physiology"),
    written("Explain the role of metarhodopsin II in the excitation cascade of photoreceptors.",
            "Light converts retinal in rhodopsin to all-trans retinal and produces metarhodopsin II. Metarhodopsin II activates transducin, which activates phosphodiesterase. cGMP falls, cGMP-gated sodium and calcium channels close, the photoreceptor hyperpolarizes, and glutamate release decreases.", "Physiology"),
    written("Compare the macula and crista ampullaris of the inner ear. Give three differences.",
            "The macula lies in the utricle and saccule and detects linear acceleration and static head position. Its sensory epithelium is covered by an otolithic membrane containing otoconia. The crista ampullaris lies in the ampulla of a semicircular duct and detects angular acceleration. Its hair bundles project into a gelatinous cupula without otoconia.", "Physiology"),
    written("Compare slow-wave sleep and rapid-eye-movement sleep. Give two differences.",
            "Slow-wave sleep has synchronized high-amplitude slow waves, reduced muscle activity, and no rapid eye movements; it occupies most normal sleep and is associated with restorative functions. REM sleep has low-voltage mixed-frequency activity, rapid eye movements, vivid dreaming, and skeletal muscle atonia; autonomic activity is variable.", "Physiology"),
    # Question VIII: Histology.
    written("Enumerate the types of neurons according to the number of fibers.",
            "Unipolar or pseudounipolar neurons, bipolar neurons, and multipolar neurons. Morphologic multipolar examples include Golgi type I, Golgi type II, stellate, pyramidal, and Purkinje cells.", "Histology"),
    written("Compare the two types of intrafusal muscle fibers of a muscle spindle.",
            "Nuclear bag fibers are larger and have a central expanded region containing a bag of nuclei. Nuclear chain fibers are thinner and have nuclei arranged in a longitudinal chain. Both lie inside the spindle capsule and receive sensory endings; gamma motor endings regulate their tension.", "Histology"),
    written("Enumerate the types of taste-bud cells seen by electron microscopy.",
            "Type I glial-like supporting cells, type II receptor cells, type III presynaptic cells, and basal cells.", "Histology"),
    written("Enumerate the different cell bodies present in the inner nuclear layer of the retina.",
            "Bipolar cells, horizontal cells, amacrine cells, and the nuclei of the supporting Muller cells.", "Histology"),
]


MCQS = [
    ("A gag reflex is elicited by lightly swabbing the oropharynx. Which cranial nerve carries the afferent limb?",
     ["Facial", "Glossopharyngeal", "Mandibular", "Maxillary", "Vagus"], "B"),
    ("An acoustic neuroma involves the vestibulocochlear nerve. In addition to hearing loss and equilibrium problems, which ipsilateral deficit is most likely?",
     ["Facial paralysis", "Loss of general sensation to the face", "Paralysis of the lateral rectus muscle", "Ptosis", "Tongue paralysis"], "A"),
    ("Which meningeal structure is located between the cerebral hemispheres?",
     ["Cavum trigeminale", "Diaphragma sellae", "Falx cerebelli", "Falx cerebri", "Tentorium cerebelli"], "D"),
    ("Cleft lip is caused by failure of fusion of which structures?",
     ["Lateral nasal prominence and maxillary process", "Lateral nasal prominence and mandibular process", "Medial nasal prominence and lateral nasal prominence", "Medial nasal prominence and maxillary process", "Medial nasal prominence and mandibular process"], "D"),
    ("About the extraocular muscles, which statement is true?",
     ["All the muscles arise from the common tendinous ring", "All the muscles are inserted onto the eyeball", "All the muscles are supplied by the oculomotor nerve", "Superior oblique depresses and abducts the eyeball", "The trochlear nerve supplies the lateral rectus muscle"], "D"),
    ("Which structure is the third neuron in the auditory pathway?",
     ["Bipolar cells of the spiral ganglion", "Cochlear nuclei", "Inferior colliculus nuclei", "Medial geniculate nuclei of the thalamus", "Neurons in the transverse temporal gyri of Heschl"], "C"),
    ("In the basal ganglia, the output center is formed by which nuclei?",
     ["Caudate nucleus and globus pallidus externus", "Globus pallidus externus and substantia nigra pars reticulata", "Globus pallidus internus and substantia nigra pars reticulata", "Putamen", "Subthalamic nucleus"], "C"),
    ("Which antidepressant has the greatest antimuscarinic effects?",
     ["Amitriptyline", "Fluoxetine", "Mirtazapine", "Nefazodone", "Trazodone"], "A"),
    ("SSRIs are much less effective than tricyclic antidepressants in the management of which condition?",
     ["Bulimia", "Chronic pain of neuropathic origin", "Generalized anxiety disorder", "Obsessive-compulsive disorder", "Premenstrual dysphoric disorder"], "B"),
    ("The primary mechanism of action of local anesthetics is:",
     ["Activation of ligand-gated potassium channels", "Blockade of GABA-gated chloride channels", "Blockade of voltage-gated sodium channels", "Blockade of calcium channels", "Stimulation of voltage-gated N-type calcium channels"], "C"),
    ("Which anesthetic is used intravenously?",
     ["Desflurane", "Halothane", "Nitrous oxide", "Propofol", "Tetracaine"], "D"),
    ("Which drug does not activate opioid receptors and blocks the effects of heroin for up to 24 hours after one oral dose?",
     ["Fentanyl", "Nalbuphine", "Naloxone", "Naltrexone", "Propoxyphene"], "D"),
    ("Which drug is a full opioid agonist with fewer withdrawal signs on abrupt discontinuance than morphine?",
     ["Fentanyl", "Hydromorphone", "Methadone", "Nalbuphine", "Oxycodone"], "C"),
    ("Which statement concerning lithium treatment of bipolar affective disorder is accurate?",
     ["High-salt foods enhance lithium toxicity", "Lithium alleviates mania within 12 hours", "Lithium dosage may need to be decreased in patients taking thiazides", "Lithium does not cross the placenta and is safe in pregnancy", "Lithium has a wide therapeutic index"], "C"),
    ("A patient prescribed buspirone for generalized anxiety disorder should anticipate:",
     ["A need to continually increase the dosage because of tolerance", "A significant effect on memory", "Additive central nervous system depression with alcohol", "That the drug may take a week or more to begin working", "Withdrawal signs if the drug is stopped abruptly"], "D"),
    ("With chronic use in seizure states, which drug causes hirsutism?",
     ["Carbamazepine", "Ethosuximide", "Phenytoin", "Tiagabine", "Zonisamide"], "C"),
    ("Carbidopa is of value in patients treated with levodopa because it:",
     ["Inhibits dopamine beta-hydroxylase", "Inhibits dopa decarboxylase", "Inhibits monoamine oxidase type A", "Inhibits neuronal reuptake of dopamine", "Releases dopamine from nerve endings"], "B"),
    ("Which condition is characterized by herniation of the cerebellum through the foramen magnum?",
     ["Microcephaly", "Dandy-Walker syndrome", "Hydrocephalus", "Chiari malformation", "Agenesis of the corpus callosum"], "D"),
    ("The basal plate gives rise to:",
     ["Motor nuclei of the cranial nerves", "Muscle cells", "Neural crest cells", "Posterior gray column of the spinal cord", "Vestibular nuclei"], "A"),
    ("How many neurons make up the olfactory pathway?",
     ["One neuron", "Two neurons", "Three neurons", "Four neurons", "Five neurons"], "B"),
    ("Light shone into the left eye causes bilateral miosis, but light shone into the right eye causes no pupillary constriction in either eye. What is the lesion?",
     ["Both optic nerves were cut", "Damage to the left oculomotor nerve", "Damage to the left optic nerve", "Damage to the right oculomotor nerve", "Damage to the right optic nerve"], "E"),
    ("A newborn develops meningitis after maternal illness from unpasteurized cheese. Which organism is most likely?",
     ["Corynebacterium diphtheriae", "Escherichia coli", "Group B streptococci", "Listeria monocytogenes", "Streptococcus pneumoniae"], "D"),
    ("After a raccoon bite, which finding would suggest that serious neurologic disease could result?",
     ["Negri-type inclusion bodies in skin scrapings", "Monoclonal antibodies on epithelial cells shed from saliva", "Negri bodies in brain tissue", "Presence of Downey cells in blood two weeks later", "Heterophile antibodies in blood"], "C"),
    ("Multiple small infarcts throughout the basal ganglia are most consistent with pathology from which artery?",
     ["Anterior cerebral artery", "Anterior communicating artery", "Lateral striate artery", "Posterior cerebral artery", "Vertebral artery"], "C"),
    ("Occlusion of the right anterior cerebral artery most likely causes a deficit in:",
     ["Motor function in the left lower limb", "Motor and sensory function in the left lower limb", "Motor and sensory function in the right lower limb", "Motor and sensory function in the upper and lower limbs", "Sensory function in the left lower limb"], "B"),
    ("Loss of pain and temperature on the right side, decreased taste on the left, hoarseness, dizziness, and nausea suggest occlusion of which artery?",
     ["Anterior cerebral artery", "Anterior inferior cerebellar artery", "Anterior spinal artery", "Posterior cerebral artery", "Posterior inferior cerebellar artery"], "E"),
    ("Which part of the cerebellum maintains equilibrium and posture?",
     ["Cerebrocerebellum", "Dentate nucleus", "Interpositus nucleus", "Spinocerebellum", "Vestibulocerebellum"], "E"),
    ("The dentatorubrothalamic tract runs through which peduncle?",
     ["Cerebral peduncle", "Inferior cerebellar peduncle", "Middle cerebellar peduncle", "Spinal cord", "Superior cerebellar peduncle"], "E"),
    ("What is the second neuron in the vestibular pathway?",
     ["Bipolar cells of the spiral ganglion", "Cells of the organ of Corti", "Cochlear nuclei", "Inferior colliculus nuclei", "Vestibular nuclei"], "E"),
    ("Glucose enters neurons mainly via which glucose transporter?",
     ["GLUT1", "GLUT2", "GLUT3", "GLUT4", "GLUT5"], "C"),
    ("During starvation, the main source of energy for the brain is:",
     ["Fatty acids", "Glycogen", "Glucose", "Glycolipid", "Ketone bodies"], "E"),
    ("Swimming in infected fresh water can transmit:",
     ["Echinococcus granulosus", "Naegleria fowleri and Acanthamoeba", "Trypanosoma cruzi", "Neurocysticercosis", "Onchocerciasis"], "B"),
    ("Narcolepsy and daytime somnolence are characteristic of:",
     ["Cerebral malaria", "Cerebral amoebic abscess", "The encephalitic stage of African trypanosomiasis", "The haemolymphatic stage of African trypanosomiasis", "Neurotoxoplasmosis"], "C"),
    ("Protozoal ocular infections that cause retinal lesions include:",
     ["African eye worm", "African trypanosomiasis", "Cysticercosis", "Onchocerciasis", "Toxoplasmosis and cerebral malaria"], "E"),
    ("A pregnant woman with fever, lymphadenopathy, and fetal hydrocephalus after contact with cats most likely has:",
     ["Cerebral malaria", "Congenital toxoplasmosis", "East African trypanosomiasis", "Primary amoebic meningoencephalitis", "West African trypanosomiasis"], "B"),
    ("Neuroschistosomiasis occurs after:",
     ["Autoinfection", "Ingestion of eggs in contaminated food", "Ingestion of encysted metacercariae in fish muscle", "Penetration of cercariae through skin or buccal mucosa", "Penetration of larvae while walking barefoot"], "D"),
    ("A brain abscess with gram-positive cocci in chains and green discoloration on blood agar is most likely caused by:",
     ["Cryptococcus neoformans", "Escherichia coli", "Staphylococcus aureus", "Streptococcus agalactiae", "Streptococcus viridans"], "E"),
    ("The vaccine used to prevent tetanus is a:",
     ["Killed virus vaccine", "Live attenuated virus vaccine", "Polysaccharide vaccine", "Recombinant vaccine", "Toxoid vaccine"], "E"),
    ("Vacuolated neurons without an immune response in a rapidly progressive fatal dementia are caused by:",
     ["A positive-sense RNA virus", "A negative-sense RNA virus", "A double-stranded DNA virus", "A single-stranded DNA virus", "Misfolded normal prion proteins"], "E"),
    ("In Chlamydia trachomatis conjunctivitis, Giemsa staining of pus shows:",
     ["Elementary bodies", "Gram-positive budding yeast cells", "Gram-negative diplococci", "Gram-positive diplococci", "Negri bodies"], "A"),
    ("A dendritic corneal ulcer in a patient without contact-lens use is most likely caused by:",
     ["Aspergillus", "Foreign body", "HSV-1", "Pseudomonas aeruginosa", "Staphylococcus aureus"], "C"),
    ("The cause of vasogenic cerebral edema is:",
     ["Greater swelling in gray matter than white matter", "Increased permeability of capillaries", "Increased permeability of neuronal membranes", "Increased production of CSF", "Intracellular accumulation of excess fluid"], "B"),
    ("Basilar meningitis with a tuberculoma is most likely caused by:",
     ["Enterovirus", "Haemophilus influenzae", "Herpes simplex virus", "Mycobacterium tuberculosis", "Streptococcus pneumoniae"], "D"),
    ("A mycotic cerebral aneurysm is most likely caused by:",
     ["Atherosclerosis of cerebral vessels", "Congenital weakness of the vessel wall", "Hypertension", "Increased intracranial tension", "Septic emboli from infective bacterial endocarditis"], "E"),
    ("Multiple sclerosis plaques would most likely show selective loss of which protein?",
     ["Beta-amyloid", "Glial fibrillary acidic protein", "Myelin", "Synaptophysin", "Synuclein"], "C"),
    ("A whorled pattern of meningothelial cells and psammoma bodies indicates:",
     ["Astrocytoma", "Ependymoma", "Glioblastoma multiforme", "Medulloblastoma", "Meningioma"], "E"),
    ("Which statement is true regarding the muscle spindle?",
     ["Activation of alpha motor neurons decreases its firing rate", "Alpha and gamma coactivation decrease its firing rate", "It emits sensory impulses continuously", "Its function is purely motor", "Shortening the spindle increases its firing rate"], "C"),
    ("Amorphosynthesis results from a lesion in:",
     ["Auditory association area 22", "Premotor area 6", "Primary motor area 4", "Somatic sensory area 1", "Somatic sensory association areas 5 and 7"], "E"),
    ("A left internal-capsule infarct is responsible for acute right hemiparesis and partial facial weakness because it contains:",
     ["The corticospinal and corticobulbar fibers", "Only the optic radiation", "Only auditory fibers", "The dorsal columns", "The spinocerebellar tracts"], "A"),
    ("Which statement is true regarding dysarthria?",
     ["Cerebellar lesions lead to slow monotonous speech", "It is a speech abnormality due to disordered articulation", "It is due to disorders in speech centers", "Lower motor neuron lesions lead to spastic speech", "Upper motor neuron lesions lead to staccato speech"], "B"),
    ("Which cortical area affects verbal and symbolic intelligence?",
     ["Amygdala", "Broca area", "Hippocampus", "Wernicke area", "Area 4"], "D"),
    ("Which brain area can initiate a complex spike pattern in Purkinje cells?",
     ["Ascending reticular formation", "Brainstem reticular nuclei", "Inferior olivary complex", "Neurons in the red nucleus", "Superior olivary complex"], "C"),
    ("Which sign is associated with cerebellar neurologic disease?",
     ["Akinesia", "Dysdiadochokinesia", "Athetosis", "Resting tremor", "Rigidity"], "B"),
    ("Which cerebellar region is responsible for planning sequential movement?",
     ["Cerebrocerebellum and dentate nucleus", "Intermediate zone and fastigial nucleus", "Lateral hemisphere and interposed nucleus", "Spinocerebellum and interposed nucleus", "Vermis and fastigial nucleus"], "A"),
    ("Narcolepsy is triggered by abnormalities in the:",
     ["Hypothalamus", "Medulla oblongata", "Neocortex", "Olfactory bulb", "Skeletal muscles"], "A"),
    ("Which statement is true regarding the role of dopamine in the basal ganglia?",
     ["It excites the direct circuit", "It excites the indirect circuit", "It is secreted from the subthalamic nuclei", "Stimulation of D1 receptors inhibits the striatum", "Stimulation of D2 receptors excites the striatum"], "A"),
    ("A patient with chronic pain, numbness, and tingling has thalamic pain syndrome. Damage to which thalamic nucleus is responsible?",
     ["Anterior nucleus", "Dorsomedial nucleus", "Pulvinar", "Ventral lateral nucleus", "Ventral posterolateral nucleus"], "E"),
    ("Beta waves are recorded in adults during brain activity mainly over the:",
     ["Frontal region", "Occipital region", "Parietal region", "Parieto-occipito-temporal region", "Temporal region"], "A"),
    ("Which is a function of the choroid of the human eye?",
     ["Fine control of focusing light onto the retina", "Contains muscles controlling pupil diameter", "Increases depth of focus for near objects", "Is the most refractive medium of the eye", "Supplies the retina with nutrients and oxygen"], "E"),
    ("A patient with glaucoma has increased intraocular pressure. What is the relevant cause or effect?",
     ["Blockage of aqueous outflow with loss of pressure in vitreous humor", "Retinal detachment", "Cataract preventing light from reaching the retina", "Increased intraocular pressure that may cause retinal damage", "Oxidation of lens crystalline proteins"], "D"),
    ("When light is shone into one eye, the pupil:",
     ["Constrics even though its optic nerve has been cut", "Responds due to sympathetic nerve activity", "Does not respond if autonomic cholinergic nerves are cut", "Constrics in that eye and the opposite pupil dilates", "Dilates in that eye"], "C"),
    ("Which statement is true concerning light refraction by the human eye?",
     ["The lens-aqueous interface provides most refraction", "Its extent is governed by pupil size", "The cornea-air interface provides most refraction", "The angle of incidence always equals the angle of refraction", "All four refractive media diverge light rays"], "C"),
    ("What is the problem with a myopic eye and how is it compensated?",
     ["Lens-retina distance is too short; use a converging lens", "Lens-retina distance is too long; use a diverging lens", "Lens-retina distance is too short; use a diverging lens", "Lens-retina distance is too long; use a converging lens", "Irregular cornea; use a cylindrical lens"], "B"),
    ("When a person enters a dimly lit room:",
     ["Cones are responsible for the second phase of adaptation", "Pupillary constriction occurs", "Rods are responsible for the first phase of adaptation", "Longer prior exposure to bright light makes dark adaptation faster", "The sensitivity of the eye for light increases"], "E"),
    ("A patient has vertigo and decreased hearing consistent with Meniere disease. Which is not a possible cause?",
     ["Blockage of the endolymphatic sac", "Decreased absorption of endolymph", "Dislocation of otolithic debris attaching to the cupula", "Increased endolymphatic fluid pressure", "Overproduction of endolymph"], "C"),
    ("Which is correct concerning volley coding for pitch discrimination?",
     ["An individual afferent fires on every wave", "Multiple frequencies are carried by a group of fibers", "Multiple frequencies are carried by a single fiber", "A single frequency is carried by a group of fibers", "A single frequency is carried by a single fiber"], "D"),
    ("Which nucleus is responsible for interaural time-delay sound localization?",
     ["Inferior olivary nuclei", "Lateral superior olivary nuclei", "Medial nucleus of the trapezoid body", "Medial superior olivary nuclei", "Pontine reticular nuclei"], "D"),
    ("Which statement is true regarding outer hair cells of the human inner ear?",
     ["They are less numerous than inner hair cells", "They contain the motor protein prestin", "They are arranged in a single row", "They have only afferent sensory function", "Their stereocilia are not embedded in the tectorial membrane"], "B"),
    ("Which is the site of olfactory sensory transduction?",
     ["Basal cells", "Cilia of olfactory bipolar cells", "Supporting cells", "Central process of olfactory bipolar cells", "Cell body of olfactory bipolar cells"], "B"),
    ("Which statement is true concerning the role of chloride in olfactory sensory transduction?",
     ["Chloride influx depolarizes the receptor neuron membrane", "Chloride outflux hyperpolarizes the receptor neuron membrane", "The equilibrium potential of chloride is about +5 mV", "Extracellular chloride concentration of about 70 mM is unusually high", "Intracellular chloride concentration of about 55 mM is unusually low"], "C"),
    ("Which statement is correct concerning dysgeusia?",
     ["It is diminished taste sensitivity in Bell palsy", "It is a foul or metallic taste persisting in the mouth", "It is lack of gustatory sensation in heavy smokers", "It is loss of olfactory sensation in otitis media", "It may be due to olfactory-groove meningioma"], "B"),
    ("Regarding the brain meninges, which statement is correct?",
     ["Arachnoid mater contains lymphatic vessels", "Arachnoid mater is highly vascularized", "Dura mater is perforated by arachnoid villi", "Pia mater is the outermost layer", "Spinal dura has an epidural space containing only fat"], "C"),
    ("Regarding the brain barriers, which statement is correct?",
     ["The blood-CSF barrier is more permeable than the blood-brain barrier", "The blood-brain barrier allows hydrophilic substances to pass freely", "The blood-brain barrier has fenestrated endothelium", "The brain-CSF barrier is strong", "Choroidal epithelial cells are interconnected by gap junctions"], "A"),
    ("The neuroepithelial structure in the ampulla of a semicircular duct is called:",
     ["Crista ampullaris", "Organ of Corti", "Saccule", "Scala vestibuli", "Utricle"], "A"),
    ("Regarding the cerebrum, which statement is correct?",
     ["Interstitial neurons are most numerous in superficial gray matter", "Islands of gray matter or nuclei are found in deep portions", "Largest pyramidal cells are present in layer III", "The cortex forms the innermost layer of the brain", "The neocortex consists of two or three layers"], "B"),
    ("A corneal abrasion that does not heal and progresses to corneal opacity most likely affected the:",
     ["Bowman membrane", "Bruch membrane", "Bulbar conjunctiva", "Corneal epithelium", "Outer limiting membrane"], "A"),
    ("The yellow pigment responsible for the yellow color of olfactory epithelium is found in:",
     ["Basal cells", "Goblet cells", "Olfactory cells", "Squamous cells", "Sustentacular cells"], "E"),
    ("The opportunistic helminthic parasite affecting the CNS is:",
     ["Echinococcus granulosus", "Heterophyes heterophyes", "Paragonimus westermani", "Schistosoma species", "Strongyloides stercoralis"], "E"),
    ("The second stage in the pathogenesis of parenchymal neurocysticercosis is the:",
     ["Colloidal stage", "Fibrous stage", "Granular-nodular stage", "Nodular-calcified stage", "Vesicular stage"], "A"),
    ("Neuropathy occurs as an indirect effect of helminthic CNS infection in:",
     ["Diphyllobothrium latum", "Echinococcus granulosus", "Ancylostoma duodenale", "Strongyloides stercoralis", "Taenia solium"], "A"),
    ("Cauda equina syndrome is the characteristic presentation of:",
     ["Cerebral schistosomiasis", "Cerebral coenurosis", "Spinal hydatidosis", "Cerebral paragonimiasis", "Cerebral trichinosis"], "C"),
    ("Which statement regarding spinal hydatid cysts is false?",
     ["The cysts do not have a well-defined border", "The cysts result from hematogenous spread", "The cysts tend to expand irregularly", "The trilaminar cyst wall is observed", "The cysts usually affect the vertebral bodies"], "A"),
    ("A patient from Cameroon sees a clear worm crossing the eye and has recurrent painless forearm swellings. What is the diagnosis?",
     ["Loiasis", "Ocular cysticercosis", "Ocular malaria", "Ocular toxoplasmosis", "River blindness"], "A"),
    ("Which intervention decreases intracranial pressure?",
     ["Blockage of foramina", "Brain tumor", "Forced expiration", "Intravenous hypertonic solutions", "Subarachnoid hemorrhage"], "D"),
    ("The change in receptor potential occurs:",
     ["In the absence of stimulation", "In mechanoreceptors through sodium influx", "As an action potential regardless of stimulus intensity", "As depolarization only", "As either depolarization or hyperpolarization"], "E"),
    ("Which statement is correct concerning slow pain?",
     ["It initiates the protective withdrawal reflex", "It is conducted along A-delta fibers", "It is conducted along type C fibers", "It is sharp, localized pricking pain that never radiates", "It is transmitted to the cerebral cortex via the lateral spinothalamic tract"], "C"),
    ("Which statement is correct concerning secondary hyperalgesia?",
     ["It is caused by central sensitization of neurons in the spinal cord", "It is confined to the area of flare", "It is confined to the area of wheal", "It is due to a local axon reflex", "It is due to peripheral sensitization of nerve terminals in injured skin"], "A"),
]


def main() -> int:
    questions = WRITTEN + [mcq(stem, options, answer) for stem, options, answer in MCQS]
    count = write_markdown(
        OUTPUT,
        "Source 6 — NEUROSCIENCE SYSTEM Final Exam 2022 (Form B)",
        {
            "Source file": "Raw_PDF_Questions/CNS/ASSIUT’S PREVIOUS EXAMS/final 2022.pdf",
            "Type": "Assiut final examination; written and MCQ sections",
            "Pages": 18,
            "Declared total": "8 essay questions and 87 MCQs; written subparts retained as individual QROC records",
            "Total questions": len(questions),
            "Question breakdown": f"{len(WRITTEN)} QROC records from the 8 essay sections; {len(MCQS)} QCS records",
            "Answer source": f"derived:{len(questions)} (essay pages are blank answer spaces and no legible MCQ key is printed)",
            "Tag": TAG,
            "Year": 2022,
            "Note": "The source is labelled Model of answer but the essay pages contain prompts and answer lines rather than completed model text; full model answers were supplied from the corresponding course content. Q72 and Q73 contain overlapping/poorly worded statements; the most defensible single options were retained and flagged here. Q86 contains two broadly true statements in the scan; C is retained as the intended single answer.",
        },
        questions,
    )
    print(f"wrote {count}; QROC={len(WRITTEN)}; QCS={len(MCQS)}; derived={count}; Arabic=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
